import type {Config} from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        code: ['"Source Code Pro"', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      colors: {
        // shadcn/ui compatibility tokens
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: 'hsl(var(--foreground))',
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        // MTN YellowConnect Design System tokens
        'primary':                '#745b00',
        'on-primary':             '#ffffff',
        'primary-container':      '#ffcc00',
        'on-primary-container':   '#6f5700',
        'primary-fixed':          '#ffe08b',
        'primary-fixed-dim':      '#f1c100',
        'on-primary-fixed':       '#241a00',
        'on-primary-fixed-variant':'#584400',
        'inverse-primary':        '#f1c100',
        'secondary':              '#1f5dae',
        'on-secondary':           '#ffffff',
        'secondary-container':    '#76a9ff',
        'on-secondary-container': '#003c7c',
        'secondary-fixed':        '#d6e3ff',
        'secondary-fixed-dim':    '#aac7ff',
        'on-secondary-fixed':     '#001b3e',
        'on-secondary-fixed-variant':'#00458d',
        'tertiary':               '#006874',
        'on-tertiary':            '#ffffff',
        'tertiary-container':     '#00e7fe',
        'on-tertiary-container':  '#00646e',
        'tertiary-fixed':         '#95f1ff',
        'tertiary-fixed-dim':     '#00daf0',
        'on-tertiary-fixed':      '#001f24',
        'on-tertiary-fixed-variant': '#004f57',
        'error':                  '#ba1a1a',
        'on-error':               '#ffffff',
        'error-container':        '#ffdad6',
        'on-error-container':     '#93000a',
        'background':             '#fcf9f8',
        'on-background':          '#1c1b1b',
        'surface':                '#fcf9f8',
        'on-surface':             '#1c1b1b',
        'surface-variant':        '#e5e2e1',
        'on-surface-variant':     '#4e4632',
        'surface-dim':            '#dcd9d9',
        'surface-bright':         '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':  '#f6f3f2',
        'surface-container':      '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'inverse-surface':        '#313030',
        'inverse-on-surface':     '#f3f0ef',
        'outline':                '#80765f',
        'outline-variant':        '#d2c5ab',
        'surface-tint':           '#745b00',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'gutter': '16px',
        'section-gap': '48px',
        'container-margin-mobile': '16px',
        'container-margin-desktop': '40px',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fadeInUp': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fadeIn': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'fade-in': 'fadeIn 1s ease-out forwards',
        'shimmer': 'shimmer 2s infinite linear',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
