'use client';

import Link from 'next/link';

export default function DownloadAnnualTaxCertificatePage() {
  return (
    <div className="bg-background text-on-surface min-h-screen pb-24">
      <header className="bg-surface flex items-center px-container-margin-mobile h-16 sticky top-0 z-50 border-b border-outline-variant/10">
        <Link href="/tax/compliance" className="material-symbols-outlined text-on-surface-variant p-2">arrow_back</Link>
        <h1 className="font-bold text-lg ml-2">Tax Certificates</h1>
      </header>

      <main className="container mx-auto px-container-margin-mobile py-8 max-w-lg">
        <div className="bg-slate-900 text-white p-10 rounded-[40px] mb-10 shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 w-48 h-48 bg-primary opacity-10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
          <div className="relative z-10">
            <span className="material-symbols-outlined text-5xl mb-6 text-primary">verified_user</span>
            <h2 className="text-3xl font-black italic mb-2">Authenticated Records</h2>
            <p className="text-white/60 text-sm leading-relaxed">
              Official tax certificates generated by MTN YellowConnect in partnership with FIRS for your annual filing requirements.
            </p>
          </div>
        </div>

        <div className="space-y-4">
          {[
            { year: '2025 Annual Clearance', id: 'TCC-2025-V1', status: 'Ready' },
            { year: '2024 Annual Clearance', id: 'TCC-2024-V4', status: 'Archive' },
          ].map(cert => (
            <div key={cert.id} className="bg-surface p-6 rounded-3xl border border-outline-variant/20 flex items-center justify-between group hover:border-primary/50 transition-all">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-surface-container-high rounded-xl flex items-center justify-center text-on-surface-variant">
                  <span className="material-symbols-outlined">description</span>
                </div>
                <div>
                  <p className="font-black text-sm">{cert.year}</p>
                  <p className="text-[10px] font-bold text-on-surface-variant uppercase font-mono">{cert.id}</p>
                </div>
              </div>
              <button className="w-12 h-12 bg-black text-white rounded-full flex items-center justify-center shadow-lg hover:scale-105 transition-transform">
                <span className="material-symbols-outlined">download</span>
              </button>
            </div>
          ))}
        </div>

        <div className="mt-12 glass-ai p-8 rounded-[40px] border border-primary/20">
          <div className="flex gap-4 items-start">
            <span className="material-symbols-outlined text-primary">gavel</span>
            <div>
              <p className="font-bold text-sm mb-2">Verification Notice</p>
              <p className="text-xs text-on-surface-variant leading-relaxed font-bold antialiased">
                Each certificate contains a unique <strong className="text-primary italic">QR Verification Code</strong>. Tax authorities can scan this to confirm the authenticity of your marketplace earnings.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
